import type { Config } from 'tailwindcss'

export default {
  content: ['./components/**/*.vue', './layouts/**/*.vue', './pages/**/*.vue', './app.vue'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'background': '#101415',
        'on-background': '#e0e3e5',
        'surface': '#101415',
        'surface-dim': '#101415',
        'surface-bright': '#363a3b',
        'surface-container-lowest': '#0b0f10',
        'surface-container-low': '#191c1e',
        'surface-container': '#1d2022',
        'surface-container-high': '#272a2c',
        'surface-container-highest': '#323537',
        'surface-variant': '#323537',
        'on-surface': '#e0e3e5',
        'on-surface-variant': '#c6c6cd',
        'inverse-surface': '#e0e3e5',
        'inverse-on-surface': '#2d3133',
        'outline': '#909097',
        'outline-variant': '#45464d',
        'surface-tint': '#bec6e0',
        'primary': '#bec6e0',
        'on-primary': '#283044',
        'primary-container': '#0f172a',
        'on-primary-container': '#798098',
        'inverse-primary': '#565e74',
        'primary-fixed': '#dae2fd',
        'primary-fixed-dim': '#bec6e0',
        'on-primary-fixed': '#131b2e',
        'on-primary-fixed-variant': '#3f465c',
        'secondary': '#adc6ff',
        'on-secondary': '#002e6a',
        'secondary-container': '#0566d9',
        'on-secondary-container': '#e6ecff',
        'secondary-fixed': '#d8e2ff',
        'secondary-fixed-dim': '#adc6ff',
        'on-secondary-fixed': '#001a42',
        'on-secondary-fixed-variant': '#004395',
        'tertiary': '#b9c8de',
        'on-tertiary': '#233143',
        'tertiary-container': '#081828',
        'on-tertiary-container': '#738296',
        'tertiary-fixed': '#d4e4fa',
        'tertiary-fixed-dim': '#b9c8de',
        'on-tertiary-fixed': '#0d1c2d',
        'on-tertiary-fixed-variant': '#39485a',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'sm': '0.125rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        mono: ['Geist', 'monospace'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '1.1', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-xl-mobile': ['40px', { lineHeight: '1.2', fontWeight: '700', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'label-mono': ['14px', { lineHeight: '1.4', fontWeight: '500', letterSpacing: '0.05em' }],
        'caption': ['12px', { lineHeight: '1.4', fontWeight: '500' }],
      },
      maxWidth: {
        'container': '1280px',
      },
      spacing: {
        'section-gap': '128px',
        'gutter': '32px',
        'margin-mobile': '20px',
        'margin-desktop': '64px',
      },
    },
  },
  plugins: [],
} satisfies Config
